"""Change player log timestamp defaults

Revision ID: 8e6f7abb3ae5
Revises: a40978bde24f
Create Date: 2022-09-11 14:01:49.765543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e6f7abb3ae5'
down_revision = 'a40978bde24f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
