"""Change default timestamp from now() to current_timeestamp()

Revision ID: 909722b9ecfe
Revises: 8e6f7abb3ae5
Create Date: 2022-09-11 14:05:50.089227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '909722b9ecfe'
down_revision = '8e6f7abb3ae5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
