"""Create Player and PlayerLog models

Revision ID: 9fe2c897acfb
Revises: 
Create Date: 2022-09-11 13:33:45.423082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fe2c897acfb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('tag', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('tag')
    )
    op.create_table('player_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_tag', sa.String(length=20), nullable=True),
    sa.Column('exp_level', sa.Integer(), nullable=True),
    sa.Column('town_hall_level', sa.Integer(), nullable=True),
    sa.Column('league', sa.String(length=25), nullable=True),
    sa.Column('trophies', sa.Integer(), nullable=True),
    sa.Column('attack_wins', sa.Integer(), nullable=True),
    sa.Column('donations_sent', sa.Integer(), nullable=True),
    sa.Column('donations_received', sa.Integer(), nullable=True),
    sa.Column('log_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['player_tag'], ['players.tag'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_logs')
    op.drop_table('players')
    # ### end Alembic commands ###
