"""Split PlayerLog model into two tables - status and activity

Revision ID: a40978bde24f
Revises: 9fe2c897acfb
Create Date: 2022-09-11 13:41:51.347531

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a40978bde24f'
down_revision = '9fe2c897acfb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_activity_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_tag', sa.String(length=20), nullable=True),
    sa.Column('league', sa.String(length=25), nullable=True),
    sa.Column('trophies', sa.Integer(), nullable=True),
    sa.Column('attack_wins', sa.Integer(), nullable=True),
    sa.Column('donations_sent', sa.Integer(), nullable=True),
    sa.Column('donations_received', sa.Integer(), nullable=True),
    sa.Column('log_date', sa.DateTime(), server_default=sa.func.current_timestamp(), nullable=True),
    sa.ForeignKeyConstraint(['player_tag'], ['players.tag'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player_status_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_tag', sa.String(length=20), nullable=True),
    sa.Column('exp_level', sa.Integer(), nullable=True),
    sa.Column('town_hall_level', sa.Integer(), nullable=True),
    sa.Column('log_date', sa.DateTime(), server_default=sa.func.current_timestamp(), nullable=True),
    sa.ForeignKeyConstraint(['player_tag'], ['players.tag'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('player_logs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_logs',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('player_tag', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('exp_level', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('town_hall_level', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('league', mysql.VARCHAR(length=25), nullable=True),
    sa.Column('trophies', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('attack_wins', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('donations_sent', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('donations_received', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('log_date', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['player_tag'], ['players.tag'], name='player_logs_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('player_status_logs')
    op.drop_table('player_activity_logs')
    # ### end Alembic commands ###
